@ECHO OFF
SETLOCAL

REM Simple Maven Wrapper launcher (generated by AI)
REM Uses .mvn\wrapper\maven-wrapper.jar to run Maven without requiring a global mvn install.

SET "MAVEN_PROJECTBASEDIR=%~dp0"

IF NOT EXIST "%MAVEN_PROJECTBASEDIR%\.mvn\wrapper\maven-wrapper.jar" (
  ECHO ERROR: .mvn\wrapper\maven-wrapper.jar not found.>&2
  ECHO Please ensure the Maven wrapper JAR is present.>&2
  EXIT /B 1
)

SET "WRAPPER_JAR=%MAVEN_PROJECTBASEDIR%\.mvn\wrapper\maven-wrapper.jar"
SET "WRAPPER_MAIN=org.apache.maven.wrapper.MavenWrapperMain"

REM Prefer JAVA_HOME if set, otherwise fall back to java on PATH
IF NOT "%JAVA_HOME%"=="" (
  SET "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
) ELSE (
  SET "JAVA_EXE=java"
)

"%JAVA_EXE%" -Dmaven.multiModuleProjectDirectory=%MAVEN_PROJECTBASEDIR% -cp "%WRAPPER_JAR%" %WRAPPER_MAIN% %*
EXIT /B %ERRORLEVEL%
